
platform :ios do
  desc "Deploy ios app on the appstore"

  lane :deploy do
    match(type: "appstore")
    cordova(platform: 'ios')
    appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end



platform :android do
  desc "Deploy android app on play store"

  # lane :debug do
  #   cordova(
  #     platform: 'android',
  #     cordova_prepare: false,
  #     release: false
  #   )
  # end

  lane :deploy do
    cordova(
      platform: 'android',
      cordova_prepare: false,
      release: true
    )
    supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
  
  lane :beta do
    cordova(
      platform: 'android',
      cordova_prepare: false,
      release: true
    )
    supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end

  lane :snap do
    # init_cordova_screenshots_android
    retrofit_cordova_screenshots_android
    gradle(
      task: 'assemble',
      build_type: 'Debug',
      project_dir: 'platforms/android'
    )
    gradle(
      task: 'assemble',
      build_type: 'AndroidTest',
      project_dir: 'platforms/android'
    )
    # screengrab
  end
end
